apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend-web
data:
  API_URL: "http://backend-clusterip-service.user-management.svc.cluster.local"
  ENVIRONMENT: "production"